### ISSUE TITLE
Seeking weights file for the model

### ISSUE THREAD

**Issue by parap1uie-s** [mueller-franzes/medfusion#1]
Hi, I recently came across your paper and was really impressed by the results. 

I was wondering if it would be possible to obtain the weights file (checkpoints) for the model used in the experiments? I would really appreciate it if you could share this, as I would like to try running the code and see if I can reproduce the results. 

Thank you in advance for your help and for making the code available.

Best regards

**Comment by mueller-franzes** [comment]
Hi,
the checkpoints are available along with the demo on Hugging Face. You can find them at https://huggingface.co/spaces/mueller-franzes/medfusion-app/tree/main/runs 

Best wishes
Gustav
