### ISSUE TITLE
'pytorch_lightning.utilities.cloud_io' Not working

### ISSUE THREAD

**Issue by stack-raghav** [mueller-franzes/medfusion#11]
Trying to run it on my pc but getting this error:

ModuleNotFoundError: No module named 'pytorch_lightning.utilities.cloud_io'

Pytorch Lightning is working fine but not this.

**Comment by stack-raghav** [comment]
I think this works for the older version of Pytorch Lightning, in the newer version, they updated this part.

**Comment by mueller-franzes** [comment]
Yes, there was indeed an update for PyTorch Lightning in which cloud_io was changed. Please try an older version, e.g. `pip install pytorch-lightning==1.8.5`.
