### ISSUE TITLE
Generated fundus images have significant artifacts

### ISSUE THREAD

**Issue by prash-p** [mueller-franzes/medfusion#2]
Hi, 

Thanks a lot for sharing the code to this project. I am using your saved checkpoints from huggingface, but I cannot seem to get good looking fundus images:

![test_None](https://user-images.githubusercontent.com/5707552/212971021-458907e8-0727-4006-aca4-71f6a823123e.png)

Many of them have two optic discs.

Meanwhile the images generated on huggingface look much better in my opinion:

![image](https://user-images.githubusercontent.com/5707552/212972080-485c36a0-ef96-495c-9e29-60204a641e70.png)

Could you also explain what 'cond' and 'un_cond' refer to in the sample.py code?

I am using the following sample.py code in the repository:

```python
from pathlib import Path
import torch 
from torchvision import utils 
import math 
from medical_diffusion.models.pipelines import DiffusionPipeline

def rgb2gray(img):
    # img [B, C, H, W]
    # return  ((0.3 * img[:,0]) + (0.59 * img[:,1]) + (0.11 * img[:,2]))[:, None]
    return  ((0.33 * img[:,0]) + (0.33 * img[:,1]) + (0.33 * img[:,2]))[:, None]

def normalize(img):
    # img =  torch.stack([b.clamp(torch.quantile(b, 0.001), torch.quantile(b, 0.999)) for b in img])
    return torch.stack([(b-b.min())/(b.max()-b.min()) for b in img])

if __name__ == "__main__":
    path_out = Path.cwd()/'results/CheXpert/samples'
    path_out.mkdir(parents=True, exist_ok=True)

    torch.manual_seed(0)
    device = torch.device('cuda')

    # ------------ Load Model ------------
    # pipeline = DiffusionPipeline.load_best_checkpoint(path_run_dir)
    pipeline = DiffusionPipeline.load_from_checkpoint('runs/eye_diffusion/last.ckpt')
    pipeline.to(device)

    
    # --------- Generate Samples  -------------------
    steps = 250
    use_ddim = True 
    images = {}
    n_samples = 4

    for cond in [0,1,None]:
        torch.manual_seed(0)
 
        # --------- Conditioning ---------
        condition = torch.tensor([cond]*n_samples, device=device) if cond is not None else None 
        # un_cond = torch.tensor([1-cond]*n_samples, device=device)
        un_cond = None 

        # ----------- Run --------
        # results = pipeline.sample(n_samples, (8, 32, 32), guidance_scale=8, condition=condition, un_cond=un_cond, steps=steps, use_ddim=use_ddim )
        results = pipeline.sample(n_samples, (4, 64, 64), guidance_scale=1, condition=condition, un_cond=un_cond, steps=steps, use_ddim=use_ddim )

        # --------- Save result ---------------
        results = (results+1)/2  # Transform from [-1, 1] to [0, 1]
        results = results.clamp(0, 1)
        utils.save_image(results, path_out/f'test_{cond}.png', nrow=int(math.sqrt(results.shape[0])), normalize=True, scale_each=True) # For 2D images: [B, C, H, W]
        images[cond] = results


    diff = torch.abs(normalize(rgb2gray(images[1]))-normalize(rgb2gray(images[0]))) # [0,1] -> [0, 1]
    # diff = torch.abs(images[1]-images[0])
    utils.save_image(diff, path_out/'diff.png', nrow=int(math.sqrt(results.shape[0])), normalize=True, scale_each=True) # For 2D images: [B, C, H, W]
```

Thank you!

**Comment by prash-p** [comment]
Okay, it seems like changing line https://github.com/mueller-franzes/medfusion/blob/main/scripts/sample.py#L46 to have initial image size (4,32,32) improves results. The resulting image is 256x256 px instead of 512x512

**Comment by mueller-franzes** [comment]
Hi, 
Yes, you have to set the size manually to match the resolution of the autoencoder's hidden space (unfortunately, I have not implemented this in a very user-friendly way, sorry). For AIROGS this was 3x256x256 (image space) -> 4x32x32 (hidden space)-> 3x256x256 (image space). 

*  'cond' refers to the condition so 0=NRG and 1 = RG 
* 'un_cond' is used for the unconditioned state with classifier-free guidance (https://arxiv.org/abs/2207.12598) (only active if you set guidance_scale != 1). For testing purposes, I tried what happens if you set "un_cond" to the other class (1-cond) instead of a neutral value (None). 
 
 I hope this answers your question and solves the issue.

**Comment by prash-p** [comment]
@mueller-franzes thanks! Does RG mean glaucoma (retinal glaucoma?), and NRG mean no glaucoma? What does cond=None mean?

**Comment by mueller-franzes** [comment]
Yes, RG = referable glaucoma, NRG = no referable glaucoma (see here https://airogs.grand-challenge.org/data-and-challenge/ ) 
cond = None means no condition - it will run the diffusion process without the condition embedding:
 https://github.com/mueller-franzes/medfusion/blob/4b92854dd1599edc091f9793390be4dea07b62e3/medical_diffusion/models/estimators/unet2.py#L236
